### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by l29** [veedeeee/BetterDiscord_SharingPrivacyFilter#1]
Nice plugin idea. I have some improvements maybe you like one of those.

- change all names and pfp from people in a group (Sidebar)
- change the dm pfp & name (https://ibb.co/LhXYqFy)
               - huger improvement: maybe make a option to doesnt show any dm name instead of dont show only the selected dm name.
- settings for custom name and pfp instead of "1"

**Comment by veedeeee** [comment]
PR is always welcome

**Comment by veedeeee** [comment]
You can choose screen capturing area. No.1 and 2 aren't needed I think.
No. 3 is pushed
